services:
    david63.sitelogo.listener:
        class: david63\sitelogo\event\listener
        arguments:
            - @config
            - @template
            - %core.root_path%			
        tags:
            - { name: event.listener }
